### ISSUE TITLE
Netlify Dev isBase64Encoded setting in lambda function's event

### ISSUE THREAD

**Issue by babycourageous** [netlify/netlify-dev-plugin#185]
Hi there

Hoping someone can shed light on this. Does running `netlify dev` in a local environment automatically run with the key/value `isBase64Encoded` set to true in the event argument of the callback? I'm submitting a simple form and the body locally is a long string of characters rather than the encoded key/value pairs received when `isBase64` runs as false (as seems to be the case live or with `netlify-lambda` serving the functions). I noticed it when having trouble parsing the body and console.logging the event running locally and comparing to the live output (as well as the output using `netlify-lambda serve`). In those cases,  `isBase64Encoded: false` is logged and the body is an encoded key/value pair string. 

If this is the expected behavior, is it just standard to be checking that `isBase64Encoded:` flag so you know how to parse the body the function receives in either environment? 

Thanks (and sorry if this is an obvious piece of knowledge!)

**Comment by sw-yx** [comment]
only if there's a Buffer: https://github.com/netlify/netlify-dev-plugin/pull/145/files

i confess i'm not too up to speed on what problems this solves or causes. if you'd like to help me review that PR and suggest what we should do instead, i am all ears.

**Comment by babycourageous** [comment]
Thanks for the quick response @sw-yx !

I too am not well versed in what problems might be involved. I'm admittedly very new to the serverless function world. In my application I'm submitting data from a form directly to the function through the form's action attribute. I just noticed that I was getting errors or results contrary to what I was getting before migrating to pure a `netlify-dev` setup without using `netlify-lambda` to serve up functions locally. 

Glancing at that pull, it does seem like isBase64Encoded should only be set if it's a Buffer coming in. But it does seem like that pull might be the culprit even though it appears to fix some other base64 issue (isn't that always the way, one solution opens another problem hehe) - especially since when running the lambda live on Netlify isBase64Encoded is set to false.

I'll keep thinking and looking though! For now, I'll just revert back to the `netlify-lambda` library so i don't have to check for three different incoming cases.

**Comment by jevets** [comment]
@babycourageous 
> I'm admittedly very new to the serverless function world.
> sorry if this is an obvious piece of knowledge!

^ You're certainly not alone on either of these!

This has been messing with me over the last couple days, actually. 

When using Netlify's Forms feature, the POST data is available as JSON in `event.body.payload`. Nice and convenient.

But when sending a good old HTML `<form method="POST">` directly to a serverless function's endpoint (no Netlify Forms), the form data is `base64` encoded on **both local dev and in production (deployed).** 

Sounds like I'm getting different results than you are: **functions in production result in `isBase64Encoded: true`** for me. I'm using `Buffer.from(string, 'base64')` to get the querystring (which I then parse into an object using `require('querystring').parse(str)`)

- Are you seeing an obvious difference in POST data when running `netlify-lambda` vs using  `netlify dev` alone locally? (I'm not running `netlify-lambda` locally, since `netlify dev` runs a functions server on `localhost:34567`)
- Are you using an HTML `<form method="POST">` element, or are you `POST`ing via a JavaScript/AJAX call?

**Comment by sw-yx** [comment]
thanks, jevets. i will ping support's help on this because i'm not knowledgeable about this

**Comment by babycourageous** [comment]
@jevets ( & @sw-yx )
That is strange that you are getting `isBase64Encoded=true` on the live netlify production environment. I'm only experiencing that on my development with `netlify-dev` - Just to be sure I set up a quick and real plain test to confirm that I was not getting base64 on Netlify's servers. It's just an index.html with a form. The form method is "post" and the action is the URL `/.netlify/functions/contact`. Below is the netlify.toml that sets up the bare bones build: 

```
[build]
  command = "# no build command"
  functions = "functions"
  publish = "."
```

The function is just a simple HELLO WORLD doing nothing but `console.log` the event and returning "Hello World" in the callback body. 

I received the form fields as a query string with isBase64Encoded=false

![image](https://user-images.githubusercontent.com/14936212/57976956-dbcc7b80-79ba-11e9-9cfc-6c46d1c29e38.png)

Hope that helps

**Comment by raeesbhatti** [comment]
Fixed in the referenced PR: https://github.com/netlify/cli/pull/398
